-- Se connecter à la base de données
\c eHotels;

-- Insertion des Chaînes Hôtelières
INSERT INTO chaine (nom, adresse, email, telephone, nombre_hotels) VALUES
('Northern Comfort', 'Toronto, Canada', 'contact@northerncomfort.com', '+1 416 555 1234', 8),
('Urban Retreats', 'New York, USA', 'info@urbanretreats.com', '+1 212 777 5678', 8),
('Sunset Resorts', 'Miami, USA', 'reservations@sunsetresorts.com', '+1 305 888 9999', 8),
('Mountain Lodges', 'Vancouver, Canada', 'info@mountainlodges.com', '+1 604 222 3333', 8),
('Caribbean Escapes', 'Nassau, Bahamas', 'bookings@caribbeanescapes.com', '+1 242 999 1111', 8);

-- Insertion des Hôtels
INSERT INTO hotel (nom, adresse, email, telephone, nombre_chambres, categorie, chaine_ID) VALUES
('Toronto Skyline Hotel', 'Toronto Skyline Hotel, Toronto, Canada', 'torontoskylinehotel@northerncomfort.com', '+2 574 661 6181', 42, 5, 1),
('Vancouver Grand Lodge', 'Vancouver Grand Lodge, Toronto, Canada', 'vancouvergrandlodge@northerncomfort.com', '+1 441 925 9798', 89, 3, 1),
('Montreal Central Stay', 'Montreal Central Stay, Toronto, Canada', 'montrealcentralstay@northerncomfort.com', '+5 102 891 7509', 49, 3, 1),
('Calgary Mountain Retreat', 'Calgary Mountain Retreat, Toronto, Canada', 'calgarymountainretreat@northerncomfort.com', '+4 335 614 9176', 61, 3, 1),
('Ottawa River Inn', 'Ottawa River Inn, Toronto, Canada', 'ottawariverinn@northerncomfort.com', '+3 240 690 2283', 42, 5, 1),
('Banff Alpine Lodge', 'Banff Alpine Lodge, Toronto, Canada', 'banffalpinelodge@northerncomfort.com', '+3 881 517 3727', 43, 5, 1),
('Quebec City Charm Hotel', 'Quebec City Charm Hotel, Toronto, Canada', 'quebeccitycharmhotel@northerncomfort.com', '+1 168 625 9999', 57, 3, 1),
('Whistler Snow Resort', 'Whistler Snow Resort, Toronto, Canada', 'whistlersnowresort@northerncomfort.com', '+2 265 210 4336', 67, 4, 1),
('New York Empire Hotel', 'New York Empire Hotel, New York, USA', 'newyorkempirehotel@urbanretreats.com', '+1 905 627 5966', 72, 4, 2),
('Los Angeles Beach View', 'Los Angeles Beach View, New York, USA', 'losangelesbeachview@urbanretreats.com', '+5 508 430 2623', 66, 4, 2),
('Chicago Skyline Suites', 'Chicago Skyline Suites, New York, USA', 'chicagoskylinesuites@urbanretreats.com', '+1 802 387 2562', 99, 5, 2),
('San Francisco Bay Resort', 'San Francisco Bay Resort, New York, USA', 'sanfranciscobayresort@urbanretreats.com', '+4 494 925 1437', 71, 5, 2),
('Miami Ocean Breeze', 'Miami Ocean Breeze, New York, USA', 'miamioceanbreeze@urbanretreats.com', '+6 367 315 2925', 50, 3, 2),
('Las Vegas Luxury Stay', 'Las Vegas Luxury Stay, New York, USA', 'lasvegasluxurystay@urbanretreats.com', '+7 568 990 5983', 49, 3, 2),
('Seattle Rainforest Inn', 'Seattle Rainforest Inn, New York, USA', 'seattlerainforestinn@urbanretreats.com', '+4 519 284 7121', 77, 3, 2),
('Houston Urban Comfort', 'Houston Urban Comfort, New York, USA', 'houstonurbancomfort@urbanretreats.com', '+6 756 685 1544', 56, 4, 2),
('Nassau Blue Lagoon', 'Nassau Blue Lagoon, Miami, USA', 'nassaubluelagoon@sunsetresorts.com', '+3 220 309 8780', 97, 3, 3),
('Montego Bay Paradise', 'Montego Bay Paradise, Miami, USA', 'montegobayparadise@sunsetresorts.com', '+4 954 901 5967', 100, 3, 3),
('Punta Cana Beachfront', 'Punta Cana Beachfront, Miami, USA', 'puntacanabeachfront@sunsetresorts.com', '+9 780 585 4548', 68, 4, 3),
('Cancun White Sands', 'Cancun White Sands, Miami, USA', 'cancunwhitesands@sunsetresorts.com', '+9 347 727 3921', 98, 3, 3),
('Aruba Sunset Resort', 'Aruba Sunset Resort, Miami, USA', 'arubasunsetresort@sunsetresorts.com', '+8 679 908 7063', 59, 5, 3),
('Bermuda Ocean Pearl', 'Bermuda Ocean Pearl, Miami, USA', 'bermudaoceanpearl@sunsetresorts.com', '+1 261 708 9466', 41, 5, 3),
('St. Lucia Palm Villas', 'St. Lucia Palm Villas, Miami, USA', 'st.luciapalmvillas@sunsetresorts.com', '+7 534 218 1066', 55, 3, 3),
('Turks & Caicos Hideaway', 'Turks & Caicos Hideaway, Miami, USA', 'turks&caicoshideaway@sunsetresorts.com', '+2 680 975 4952', 43, 5, 3),
('Boston Harbor Hotel', 'Boston Harbor Hotel, Vancouver, Canada', 'bostonharborhotel@mountainlodges.com', '+8 896 406 9434', 49, 3, 4),
('Denver Rocky Stay', 'Denver Rocky Stay, Vancouver, Canada', 'denverrockystay@mountainlodges.com', '+4 212 514 5444', 93, 4, 4),
('Phoenix Desert Oasis', 'Phoenix Desert Oasis, Vancouver, Canada', 'phoenixdesertoasis@mountainlodges.com', '+5 558 249 2849', 42, 4, 4),
('Atlanta Skyline Suites', 'Atlanta Skyline Suites, Vancouver, Canada', 'atlantaskylinesuites@mountainlodges.com', '+9 758 435 3001', 57, 4, 4),
('Orlando Family Resort', 'Orlando Family Resort, Vancouver, Canada', 'orlandofamilyresort@mountainlodges.com', '+7 373 271 1833', 85, 4, 4),
('Dallas Lone Star Inn', 'Dallas Lone Star Inn, Vancouver, Canada', 'dallaslonestarinn@mountainlodges.com', '+6 586 433 6830', 81, 4, 4),
('San Diego Sunset Lodge', 'San Diego Sunset Lodge, Vancouver, Canada', 'sandiegosunsetlodge@mountainlodges.com', '+5 714 902 8909', 91, 3, 4),
('Anchorage Northern Lights Lodge', 'Anchorage Northern Lights Lodge, Vancouver, Canada', 'anchoragenorthernlightslodge@mountainlodges.com', '+9 678 158 7598', 40, 3, 4);

-- Insertion des Chambres
INSERT INTO chambre (prix, commodites, capacite, vue, problemes, extensible, hotel_ID) VALUES
(169.84, 'WiFi, TV, Terrasse', 2, 'Vue sur jardin', NULL, FALSE, 1),
(262.1, 'WiFi, TV, Jacuzzi', 4, 'Vue sur montagne', 'Climatisation en panne', FALSE, 1),
(269.76, 'WiFi, TV, Piscine privée', 3, 'Vue sur montagne', 'Climatisation en panne', TRUE, 1),
(332.39, 'WiFi, TV, Terrasse', 2, 'Vue sur mer', NULL, TRUE, 1),
(389.09, 'WiFi, TV, Climatisation', 1, 'Vue sur ville', 'Climatisation en panne', FALSE, 1),
(213.79, 'WiFi, TV, Terrasse', 2, 'Vue sur montagne', 'Climatisation en panne', FALSE, 2),
(131.81, 'WiFi, TV, Climatisation', 1, 'Vue sur mer', 'Climatisation en panne', FALSE, 2),
(300.71, 'WiFi, TV, Mini-bar', 5, 'Vue sur montagne', 'Climatisation en panne', FALSE, 2),
(388.14, 'WiFi, TV, Climatisation', 3, 'Vue sur ville', 'Climatisation en panne', TRUE, 2),
(301.84, 'WiFi, TV, Jacuzzi', 5, 'Vue sur lac', 'Climatisation en panne', FALSE, 2),
(247.09, 'WiFi, TV, Climatisation', 1, 'Vue sur montagne', NULL, TRUE, 3),
(206.65, 'WiFi, TV, Piscine privée', 4, 'Vue sur jardin', 'Climatisation en panne', FALSE, 3),
(161.72, 'WiFi, TV, Terrasse', 3, 'Vue sur lac', 'Climatisation en panne', TRUE, 3),
(146.11, 'WiFi, TV, Piscine privée', 4, 'Vue sur mer', 'Climatisation en panne', TRUE, 3),
(265.41, 'WiFi, TV, Jacuzzi', 2, 'Vue sur lac', 'Climatisation en panne', TRUE, 3),
(114.0, 'WiFi, TV, Piscine privée', 2, 'Vue sur ville', 'Climatisation en panne', TRUE, 4),
(241.43, 'WiFi, TV, Mini-bar', 3, 'Vue sur montagne', 'Climatisation en panne', TRUE, 4),
(320.73, 'WiFi, TV, Terrasse', 2, 'Vue sur montagne', 'Climatisation en panne', FALSE, 4),
(135.37, 'WiFi, TV, Mini-bar', 1, 'Vue sur mer', 'Climatisation en panne', FALSE, 4),
(219.77, 'WiFi, TV, Climatisation', 4, 'Vue sur jardin', 'Climatisation en panne', FALSE, 4),
(153.61, 'WiFi, TV, Climatisation', 4, 'Vue sur mer', 'Climatisation en panne', FALSE, 5),
(369.52, 'WiFi, TV, Jacuzzi', 4, 'Vue sur mer', 'Climatisation en panne', FALSE, 5),
(193.49, 'WiFi, TV, Piscine privée', 5, 'Vue sur jardin', 'Climatisation en panne', FALSE, 5),
(126.46, 'WiFi, TV, Jacuzzi', 5, 'Vue sur jardin', 'Climatisation en panne', TRUE, 5),
(269.3, 'WiFi, TV, Piscine privée', 3, 'Vue sur lac', 'Climatisation en panne', TRUE, 5),
(215.78, 'WiFi, TV, Jacuzzi', 3, 'Vue sur lac', 'Climatisation en panne', FALSE, 6),
(316.04, 'WiFi, TV, Piscine privée', 4, 'Vue sur lac', 'Climatisation en panne', TRUE, 6),
(295.16, 'WiFi, TV, Jacuzzi', 5, 'Vue sur montagne', 'Climatisation en panne', FALSE, 6),
(280.38, 'WiFi, TV, Climatisation', 4, 'Vue sur montagne', NULL, FALSE, 6),
(397.0, 'WiFi, TV, Mini-bar', 1, 'Vue sur ville', 'Climatisation en panne', TRUE, 6),
(294.82, 'WiFi, TV, Terrasse', 4, 'Vue sur mer', 'Climatisation en panne', TRUE, 7),
(261.25, 'WiFi, TV, Mini-bar', 2, 'Vue sur mer', 'Climatisation en panne', FALSE, 7),
(297.81, 'WiFi, TV, Climatisation', 4, 'Vue sur jardin', NULL, TRUE, 7),
(323.58, 'WiFi, TV, Mini-bar', 4, 'Vue sur jardin', NULL, TRUE, 7),
(365.38, 'WiFi, TV, Piscine privée', 4, 'Vue sur jardin', 'Climatisation en panne', FALSE, 7),
(373.27, 'WiFi, TV, Terrasse', 4, 'Vue sur montagne', 'Climatisation en panne', TRUE, 8),
(330.26, 'WiFi, TV, Terrasse', 1, 'Vue sur mer', NULL, TRUE, 8),
(348.18, 'WiFi, TV, Mini-bar', 1, 'Vue sur mer', 'Climatisation en panne', FALSE, 8),
(297.6, 'WiFi, TV, Mini-bar', 4, 'Vue sur ville', NULL, TRUE, 8),
(124.05, 'WiFi, TV, Mini-bar', 5, 'Vue sur jardin', 'Climatisation en panne', TRUE, 8),
(164.37, 'WiFi, TV, Mini-bar', 5, 'Vue sur lac', 'Climatisation en panne', TRUE, 9),
(248.36, 'WiFi, TV, Piscine privée', 4, 'Vue sur jardin', 'Climatisation en panne', FALSE, 9),
(321.8, 'WiFi, TV, Mini-bar', 5, 'Vue sur montagne', 'Climatisation en panne', FALSE, 9),
(245.5, 'WiFi, TV, Terrasse', 1, 'Vue sur ville', 'Climatisation en panne', TRUE, 9),
(369.99, 'WiFi, TV, Terrasse', 2, 'Vue sur ville', NULL, TRUE, 9),
(349.96, 'WiFi, TV, Piscine privée', 1, 'Vue sur jardin', 'Climatisation en panne', FALSE, 10),
(115.91, 'WiFi, TV, Mini-bar', 3, 'Vue sur jardin', NULL, FALSE, 10),
(133.03, 'WiFi, TV, Jacuzzi', 3, 'Vue sur lac', 'Climatisation en panne', TRUE, 10),
(312.34, 'WiFi, TV, Piscine privée', 3, 'Vue sur lac', NULL, TRUE, 10),
(383.02, 'WiFi, TV, Jacuzzi', 2, 'Vue sur jardin', 'Climatisation en panne', FALSE, 10),
(113.75, 'WiFi, TV, Terrasse', 2, 'Vue sur lac', 'Climatisation en panne', TRUE, 11),
(269.58, 'WiFi, TV, Climatisation', 2, 'Vue sur ville', 'Climatisation en panne', FALSE, 11),
(142.2, 'WiFi, TV, Mini-bar', 2, 'Vue sur mer', 'Climatisation en panne', FALSE, 11),
(122.61, 'WiFi, TV, Terrasse', 2, 'Vue sur lac', 'Climatisation en panne', FALSE, 11),
(320.55, 'WiFi, TV, Climatisation', 2, 'Vue sur mer', 'Climatisation en panne', TRUE, 11),
(262.91, 'WiFi, TV, Piscine privée', 1, 'Vue sur ville', 'Climatisation en panne', TRUE, 12),
(142.57, 'WiFi, TV, Mini-bar', 2, 'Vue sur montagne', NULL, FALSE, 12),
(140.0, 'WiFi, TV, Piscine privée', 5, 'Vue sur montagne', 'Climatisation en panne', TRUE, 12),
(170.08, 'WiFi, TV, Mini-bar', 3, 'Vue sur mer', 'Climatisation en panne', FALSE, 12),
(112.86, 'WiFi, TV, Climatisation', 1, 'Vue sur montagne', 'Climatisation en panne', TRUE, 12),
(117.72, 'WiFi, TV, Mini-bar', 5, 'Vue sur montagne', 'Climatisation en panne', TRUE, 13),
(136.26, 'WiFi, TV, Piscine privée', 1, 'Vue sur mer', 'Climatisation en panne', FALSE, 13),
(387.79, 'WiFi, TV, Climatisation', 5, 'Vue sur mer', 'Climatisation en panne', FALSE, 13),
(345.39, 'WiFi, TV, Climatisation', 2, 'Vue sur montagne', 'Climatisation en panne', TRUE, 13),
(133.14, 'WiFi, TV, Jacuzzi', 4, 'Vue sur lac', 'Climatisation en panne', TRUE, 13),
(176.9, 'WiFi, TV, Terrasse', 1, 'Vue sur jardin', 'Climatisation en panne', TRUE, 14),
(237.35, 'WiFi, TV, Terrasse', 3, 'Vue sur montagne', 'Climatisation en panne', FALSE, 14),
(282.45, 'WiFi, TV, Terrasse', 3, 'Vue sur mer', NULL, TRUE, 14),
(260.05, 'WiFi, TV, Climatisation', 1, 'Vue sur montagne', NULL, FALSE, 14),
(282.56, 'WiFi, TV, Piscine privée', 4, 'Vue sur montagne', 'Climatisation en panne', FALSE, 14),
(252.25, 'WiFi, TV, Jacuzzi', 3, 'Vue sur mer', NULL, TRUE, 15),
(102.77, 'WiFi, TV, Jacuzzi', 5, 'Vue sur mer', NULL, TRUE, 15),
(264.65, 'WiFi, TV, Piscine privée', 5, 'Vue sur mer', 'Climatisation en panne', FALSE, 15),
(336.89, 'WiFi, TV, Terrasse', 3, 'Vue sur mer', NULL, TRUE, 15),
(133.35, 'WiFi, TV, Climatisation', 2, 'Vue sur jardin', 'Climatisation en panne', FALSE, 15),
(113.79, 'WiFi, TV, Jacuzzi', 4, 'Vue sur lac', 'Climatisation en panne', TRUE, 16),
(119.05, 'WiFi, TV, Terrasse', 2, 'Vue sur mer', 'Climatisation en panne', TRUE, 16),
(286.79, 'WiFi, TV, Piscine privée', 3, 'Vue sur mer', NULL, TRUE, 16),
(138.68, 'WiFi, TV, Terrasse', 5, 'Vue sur mer', NULL, FALSE, 16),
(161.01, 'WiFi, TV, Piscine privée', 5, 'Vue sur ville', 'Climatisation en panne', FALSE, 16),
(282.82, 'WiFi, TV, Climatisation', 4, 'Vue sur montagne', 'Climatisation en panne', TRUE, 17),
(163.86, 'WiFi, TV, Mini-bar', 3, 'Vue sur lac', 'Climatisation en panne', TRUE, 17),
(378.78, 'WiFi, TV, Piscine privée', 2, 'Vue sur ville', NULL, TRUE, 17),
(190.64, 'WiFi, TV, Jacuzzi', 3, 'Vue sur lac', 'Climatisation en panne', FALSE, 17),
(179.92, 'WiFi, TV, Climatisation', 5, 'Vue sur lac', 'Climatisation en panne', TRUE, 17),
(384.74, 'WiFi, TV, Piscine privée', 3, 'Vue sur lac', 'Climatisation en panne', FALSE, 18),
(129.86, 'WiFi, TV, Terrasse', 5, 'Vue sur ville', 'Climatisation en panne', FALSE, 18),
(172.62, 'WiFi, TV, Piscine privée', 5, 'Vue sur montagne', 'Climatisation en panne', TRUE, 18),
(305.11, 'WiFi, TV, Jacuzzi', 1, 'Vue sur lac', NULL, TRUE, 18),
(316.39, 'WiFi, TV, Mini-bar', 5, 'Vue sur mer', NULL, TRUE, 18),
(237.46, 'WiFi, TV, Jacuzzi', 3, 'Vue sur lac', NULL, TRUE, 19),
(231.97, 'WiFi, TV, Piscine privée', 5, 'Vue sur montagne', 'Climatisation en panne', FALSE, 19),
(396.07, 'WiFi, TV, Climatisation', 3, 'Vue sur lac', 'Climatisation en panne', TRUE, 19),
(134.33, 'WiFi, TV, Piscine privée', 1, 'Vue sur jardin', 'Climatisation en panne', FALSE, 19),
(300.44, 'WiFi, TV, Terrasse', 1, 'Vue sur ville', 'Climatisation en panne', TRUE, 19),
(312.01, 'WiFi, TV, Jacuzzi', 4, 'Vue sur lac', 'Climatisation en panne', TRUE, 20),
(363.28, 'WiFi, TV, Jacuzzi', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 20),
(100.71, 'WiFi, TV, Piscine privée', 3, 'Vue sur montagne', NULL, FALSE, 20),
(167.7, 'WiFi, TV, Piscine privée', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 20),
(303.65, 'WiFi, TV, Climatisation', 3, 'Vue sur mer', NULL, FALSE, 20),
(336.48, 'WiFi, TV, Mini-bar', 3, 'Vue sur montagne', NULL, FALSE, 21),
(396.57, 'WiFi, TV, Terrasse', 4, 'Vue sur montagne', 'Climatisation en panne', TRUE, 21),
(381.52, 'WiFi, TV, Terrasse', 3, 'Vue sur lac', 'Climatisation en panne', FALSE, 21),
(247.97, 'WiFi, TV, Piscine privée', 5, 'Vue sur montagne', 'Climatisation en panne', FALSE, 21),
(338.75, 'WiFi, TV, Mini-bar', 5, 'Vue sur ville', NULL, TRUE, 21),
(342.75, 'WiFi, TV, Mini-bar', 4, 'Vue sur mer', 'Climatisation en panne', FALSE, 22),
(148.11, 'WiFi, TV, Jacuzzi', 1, 'Vue sur jardin', NULL, FALSE, 22),
(316.47, 'WiFi, TV, Jacuzzi', 2, 'Vue sur lac', 'Climatisation en panne', TRUE, 22),
(165.05, 'WiFi, TV, Piscine privée', 2, 'Vue sur jardin', 'Climatisation en panne', FALSE, 22),
(385.38, 'WiFi, TV, Mini-bar', 2, 'Vue sur jardin', 'Climatisation en panne', TRUE, 22),
(387.14, 'WiFi, TV, Piscine privée', 1, 'Vue sur montagne', NULL, FALSE, 23),
(288.64, 'WiFi, TV, Terrasse', 2, 'Vue sur lac', 'Climatisation en panne', TRUE, 23),
(236.81, 'WiFi, TV, Mini-bar', 2, 'Vue sur lac', 'Climatisation en panne', FALSE, 23),
(122.8, 'WiFi, TV, Terrasse', 5, 'Vue sur montagne', 'Climatisation en panne', TRUE, 23),
(148.96, 'WiFi, TV, Jacuzzi', 4, 'Vue sur jardin', 'Climatisation en panne', TRUE, 23),
(292.16, 'WiFi, TV, Jacuzzi', 5, 'Vue sur jardin', 'Climatisation en panne', FALSE, 24),
(169.5, 'WiFi, TV, Mini-bar', 4, 'Vue sur lac', 'Climatisation en panne', FALSE, 24),
(292.26, 'WiFi, TV, Terrasse', 5, 'Vue sur mer', 'Climatisation en panne', FALSE, 24),
(181.54, 'WiFi, TV, Piscine privée', 3, 'Vue sur ville', 'Climatisation en panne', TRUE, 24),
(186.35, 'WiFi, TV, Jacuzzi', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 24),
(245.33, 'WiFi, TV, Piscine privée', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 25),
(378.72, 'WiFi, TV, Jacuzzi', 1, 'Vue sur ville', NULL, FALSE, 25),
(321.35, 'WiFi, TV, Jacuzzi', 5, 'Vue sur ville', 'Climatisation en panne', FALSE, 25),
(107.41, 'WiFi, TV, Jacuzzi', 4, 'Vue sur montagne', 'Climatisation en panne', FALSE, 25),
(118.45, 'WiFi, TV, Terrasse', 5, 'Vue sur ville', 'Climatisation en panne', FALSE, 25),
(118.0, 'WiFi, TV, Mini-bar', 1, 'Vue sur lac', NULL, FALSE, 26),
(305.19, 'WiFi, TV, Climatisation', 4, 'Vue sur lac', 'Climatisation en panne', FALSE, 26),
(341.76, 'WiFi, TV, Terrasse', 4, 'Vue sur mer', 'Climatisation en panne', TRUE, 26),
(340.19, 'WiFi, TV, Piscine privée', 4, 'Vue sur montagne', 'Climatisation en panne', FALSE, 26),
(307.26, 'WiFi, TV, Terrasse', 4, 'Vue sur mer', 'Climatisation en panne', FALSE, 26),
(153.89, 'WiFi, TV, Piscine privée', 4, 'Vue sur jardin', 'Climatisation en panne', FALSE, 27),
(216.39, 'WiFi, TV, Climatisation', 3, 'Vue sur ville', 'Climatisation en panne', TRUE, 27),
(262.63, 'WiFi, TV, Terrasse', 1, 'Vue sur montagne', NULL, TRUE, 27),
(279.35, 'WiFi, TV, Climatisation', 1, 'Vue sur ville', 'Climatisation en panne', TRUE, 27),
(233.66, 'WiFi, TV, Climatisation', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 27),
(136.62, 'WiFi, TV, Mini-bar', 2, 'Vue sur ville', 'Climatisation en panne', TRUE, 28),
(366.81, 'WiFi, TV, Piscine privée', 3, 'Vue sur jardin', 'Climatisation en panne', FALSE, 28),
(331.19, 'WiFi, TV, Piscine privée', 2, 'Vue sur ville', 'Climatisation en panne', TRUE, 28),
(392.71, 'WiFi, TV, Jacuzzi', 1, 'Vue sur montagne', 'Climatisation en panne', TRUE, 28),
(228.02, 'WiFi, TV, Terrasse', 1, 'Vue sur ville', 'Climatisation en panne', TRUE, 28),
(338.97, 'WiFi, TV, Mini-bar', 5, 'Vue sur lac', 'Climatisation en panne', FALSE, 29),
(246.31, 'WiFi, TV, Piscine privée', 3, 'Vue sur montagne', 'Climatisation en panne', FALSE, 29),
(236.96, 'WiFi, TV, Terrasse', 3, 'Vue sur ville', 'Climatisation en panne', TRUE, 29),
(169.93, 'WiFi, TV, Piscine privée', 2, 'Vue sur lac', 'Climatisation en panne', FALSE, 29),
(356.35, 'WiFi, TV, Terrasse', 4, 'Vue sur mer', 'Climatisation en panne', FALSE, 29),
(115.65, 'WiFi, TV, Climatisation', 5, 'Vue sur mer', NULL, FALSE, 30),
(399.81, 'WiFi, TV, Mini-bar', 4, 'Vue sur mer', 'Climatisation en panne', FALSE, 30),
(193.41, 'WiFi, TV, Piscine privée', 5, 'Vue sur lac', NULL, TRUE, 30),
(379.52, 'WiFi, TV, Terrasse', 1, 'Vue sur montagne', 'Climatisation en panne', TRUE, 30),
(377.91, 'WiFi, TV, Climatisation', 2, 'Vue sur lac', 'Climatisation en panne', FALSE, 30),
(257.91, 'WiFi, TV, Climatisation', 3, 'Vue sur jardin', 'Climatisation en panne', FALSE, 31),
(384.4, 'WiFi, TV, Jacuzzi', 4, 'Vue sur lac', 'Climatisation en panne', FALSE, 31),
(156.26, 'WiFi, TV, Terrasse', 4, 'Vue sur montagne', NULL, FALSE, 31),
(270.07, 'WiFi, TV, Climatisation', 5, 'Vue sur lac', NULL, TRUE, 31),
(179.11, 'WiFi, TV, Terrasse', 1, 'Vue sur montagne', 'Climatisation en panne', FALSE, 31),
(356.16, 'WiFi, TV, Jacuzzi', 1, 'Vue sur lac', NULL, TRUE, 32),
(313.4, 'WiFi, TV, Terrasse', 1, 'Vue sur montagne', NULL, TRUE, 32),
(253.08, 'WiFi, TV, Jacuzzi', 4, 'Vue sur montagne', 'Climatisation en panne', FALSE, 32),
(394.64, 'WiFi, TV, Climatisation', 3, 'Vue sur montagne', 'Climatisation en panne', TRUE, 32),
(278.41, 'WiFi, TV, Climatisation', 2, 'Vue sur montagne', 'Climatisation en panne', FALSE, 32),
(135.62, 'WiFi, TV, Jacuzzi', 1, 'Vue sur mer', 'Climatisation en panne', TRUE, 33),
(101.64, 'WiFi, TV, Mini-bar', 4, 'Vue sur jardin', 'Climatisation en panne', FALSE, 33),
(131.96, 'WiFi, TV, Mini-bar', 1, 'Vue sur mer', 'Climatisation en panne', TRUE, 33),
(331.91, 'WiFi, TV, Terrasse', 5, 'Vue sur jardin', 'Climatisation en panne', FALSE, 33),
(225.97, 'WiFi, TV, Terrasse', 4, 'Vue sur mer', NULL, FALSE, 33),
(281.07, 'WiFi, TV, Mini-bar', 2, 'Vue sur ville', NULL, FALSE, 34),
(253.85, 'WiFi, TV, Mini-bar', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 34),
(285.95, 'WiFi, TV, Terrasse', 1, 'Vue sur ville', 'Climatisation en panne', FALSE, 34),
(191.81, 'WiFi, TV, Piscine privée', 1, 'Vue sur ville', 'Climatisation en panne', FALSE, 34),
(156.0, 'WiFi, TV, Jacuzzi', 5, 'Vue sur jardin', 'Climatisation en panne', FALSE, 34),
(223.73, 'WiFi, TV, Climatisation', 2, 'Vue sur ville', 'Climatisation en panne', TRUE, 35),
(197.72, 'WiFi, TV, Piscine privée', 3, 'Vue sur mer', 'Climatisation en panne', TRUE, 35),
(119.52, 'WiFi, TV, Climatisation', 5, 'Vue sur mer', 'Climatisation en panne', FALSE, 35),
(136.29, 'WiFi, TV, Jacuzzi', 3, 'Vue sur jardin', NULL, FALSE, 35),
(204.03, 'WiFi, TV, Climatisation', 5, 'Vue sur jardin', NULL, TRUE, 35),
(372.69, 'WiFi, TV, Piscine privée', 5, 'Vue sur mer', 'Climatisation en panne', FALSE, 36),
(110.84, 'WiFi, TV, Piscine privée', 3, 'Vue sur montagne', NULL, TRUE, 36),
(270.87, 'WiFi, TV, Terrasse', 4, 'Vue sur ville', 'Climatisation en panne', TRUE, 36),
(203.41, 'WiFi, TV, Climatisation', 5, 'Vue sur lac', NULL, TRUE, 36),
(318.19, 'WiFi, TV, Climatisation', 4, 'Vue sur montagne', 'Climatisation en panne', FALSE, 36),
(195.13, 'WiFi, TV, Terrasse', 5, 'Vue sur mer', NULL, TRUE, 37),
(386.71, 'WiFi, TV, Climatisation', 1, 'Vue sur jardin', 'Climatisation en panne', FALSE, 37),
(153.45, 'WiFi, TV, Jacuzzi', 4, 'Vue sur lac', NULL, TRUE, 37),
(105.22, 'WiFi, TV, Climatisation', 1, 'Vue sur mer', 'Climatisation en panne', FALSE, 37),
(179.15, 'WiFi, TV, Jacuzzi', 5, 'Vue sur ville', 'Climatisation en panne', FALSE, 37),
(325.41, 'WiFi, TV, Terrasse', 2, 'Vue sur ville', 'Climatisation en panne', FALSE, 38),
(141.12, 'WiFi, TV, Jacuzzi', 2, 'Vue sur lac', 'Climatisation en panne', TRUE, 38),
(341.53, 'WiFi, TV, Piscine privée', 5, 'Vue sur mer', NULL, FALSE, 38),
(135.53, 'WiFi, TV, Piscine privée', 3, 'Vue sur lac', 'Climatisation en panne', FALSE, 38),
(341.48, 'WiFi, TV, Jacuzzi', 2, 'Vue sur ville', 'Climatisation en panne', FALSE, 38),
(149.39, 'WiFi, TV, Terrasse', 1, 'Vue sur mer', 'Climatisation en panne', TRUE, 39),
(211.17, 'WiFi, TV, Climatisation', 5, 'Vue sur mer', 'Climatisation en panne', TRUE, 39),
(305.72, 'WiFi, TV, Piscine privée', 3, 'Vue sur lac', 'Climatisation en panne', FALSE, 39),
(106.87, 'WiFi, TV, Piscine privée', 3, 'Vue sur ville', 'Climatisation en panne', FALSE, 39),
(122.68, 'WiFi, TV, Piscine privée', 4, 'Vue sur ville', 'Climatisation en panne', FALSE, 39),
(322.76, 'WiFi, TV, Jacuzzi', 4, 'Vue sur lac', 'Climatisation en panne', FALSE, 40),
(153.71, 'WiFi, TV, Jacuzzi', 3, 'Vue sur montagne', 'Climatisation en panne', FALSE, 40),
(112.72, 'WiFi, TV, Piscine privée', 3, 'Vue sur jardin', 'Climatisation en panne', TRUE, 40),
(184.27, 'WiFi, TV, Mini-bar', 4, 'Vue sur mer', 'Climatisation en panne', TRUE, 40),
(119.77, 'WiFi, TV, Climatisation', 5, 'Vue sur lac', 'Climatisation en panne', TRUE, 40);

-- Insertion des Gestionnaires
INSERT INTO employe (NAS, nom, prénom, adresse, rôle, hotel_ID) VALUES
(101223456, 'Lavoie', 'Jean-Marc', '123 Queen St, Toronto, Canada', 'Gestionnaire', 1),
(102334567, 'Smith', 'Rebecca', '456 5th Avenue, New York, USA', 'Gestionnaire', 9),
(103445678, 'Gonzalez', 'Luis', '789 Ocean Drive, Miami, USA', 'Gestionnaire', 17),
(104556789, 'Williams', 'Sophie', '321 Mountain Rd, Vancouver, Canada', 'Gestionnaire', 25),
(105667890, 'Dupont', 'Antoine', '654 Paradise Beach, Nassau, Bahamas', 'Gestionnaire', 33);
